services:
  # Traefik 反向代理
  traefik:
    image: traefik:v3.5
    container_name: traefik-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik-external.yml:/etc/traefik/external.yml:ro
      - ./traefik-data:/data
    networks:
      - app-maker-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${PROD_DOMAIN_NAME:-thought-light.com}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"

  # AutoCodeWeb 前端服务 (生产环境 - Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Uses the new prod Dockerfile
    container_name: app-maker-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
      - traefik
    networks:
      - app-maker-network
    labels:
      # 用于 Traefik 服务发现
      - "traefik.enable=true"
      - "traefik.docker.network=app-maker-network"
      # HTTP 相关
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.rule=Host(`${PROD_DOMAIN_NAME:-thought-light.com}`)"
      - "traefik.http.routers.frontend-http.service=frontend-service"
      # 声明服务名称为 frontend-service，使用 80 端口提供服务
      - "traefik.http.services.frontend-service.loadbalancer.server.scheme=http"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=80"

  # AutoCodeWeb 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: app-maker-backend-prod
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=production
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOG_LEVEL=warn
    volumes:
      - ./backend/configs:/app/configs:ro
      - ./backend/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      traefik:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-maker-network
    labels:
      # 用于 Traefik 服务发现
      - "traefik.enable=true"
      - "traefik.docker.network=app-maker-network"
      # HTTP 相关
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.rule=Host(`api.${PROD_DOMAIN_NAME:-thought-light.com}`)"
      - "traefik.http.routers.backend-http.service=backend-service"
      # 声明服务名称为 backend-service，使用 8080 端口提供服务
      - "traefik.http.services.backend-service.loadbalancer.server.scheme=http"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8080"

  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: app-maker-postgres-prod
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-maker-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: app-maker-redis-prod
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-maker-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-maker-network:
    external: true