version: '3.8'

services:
  # AutoCodeWeb 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: autocodeweb-backend-prod
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=production
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOG_LEVEL=warn
    volumes:
      - ./configs:/app/configs:ro
      - ./logs:/app/logs
      - ./bmad-config:/app/bmad-config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - autocodeweb-prod-network

  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: autocodeweb-postgres-prod
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - autocodeweb-prod-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: autocodeweb-redis-prod
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - autocodeweb-prod-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  autocodeweb-prod-network:
    driver: bridge
