\c autocodeweb;

ALTER TABLE dev_stages 
ADD COLUMN IF NOT EXISTS need_confirm BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE dev_stages 
ADD COLUMN IF NOT EXISTS user_confirmed BOOLEAN NOT NULL DEFAULT FALSE;