app:
  environment: "development"
  port: "8080"
  secret_key: "dev-secret-key-change-in-production"

database:
  host: "postgres"
  port: 5434
  user: "autocodeweb"
  password: "AutoCodeWeb2024!@#"
  name: "autocodeweb"
  ssl_mode: "disable"
  # 数据库连接超时设置
  connect_timeout: 10
  # 数据库迁移设置
  auto_migrate: true
  # 数据库种子数据
  seed_data: true

redis:
  host: "autocodeweb-redis-dev"
  port: 6379
  password: ""
  db: 0

jwt:
  secret_key: "dev-jwt-secret-key-change-in-production"
  expire_hours: 24

bmad:
  npm_package: "bmad-method"
  config_path: "./bmad-config"

log:
  level: "info"
  file: "./logs/app.log"
