app:
  environment: "development"
  port: "8080"
  secret_key: "dev-secret-key-change-in-production"

database:
  host: "autocodeweb-postgres"
  port: 5432
  user: "autocodeweb"
  password: "AutoCodeWeb2024!@#"
  name: "autocodeweb"
  ssl_mode: "disable"
  connect_timeout: 10
  auto_migrate: true
  seed_data: true

redis:
  host: "autocodeweb-redis"
  port: 6379
  password: ""
  db: 0

jwt:
  secret_key: "dev-jwt-secret-key-change-in-production"
  expire_hours: 24

bmad:
  npm_package: "bmad-method"

ai:
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.2:latest"
    timeout: 30

log:
  level: "debug"
  file: "./logs/app.log"
